(() => {
  'use strict';
  const {Game,reflections,GROUND,WORLD}=window.CraftGame;
  const game=new Game(), canvas=document.getElementById('game'), ctx=canvas.getContext('2d');
  const overlay=document.getElementById('overlay'),panel=document.getElementById('panel'),toast=document.getElementById('toast');
  const keys=new Set(),touch=new Set();let camera=0,last=0,returnState='playing',currentReflection=0,afterReflection=null,toastTimer;
  const colors={outline:'#344536',cardboard:'#cb9e68'};
  function clearInput(){keys.clear();touch.clear();game.jumpBuffer=0;document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));}
  function show(html){clearInput();panel.innerHTML=html;overlay.hidden=false;panel.scrollTop=0;const first=panel.querySelector('button');if(first)first.focus({preventScroll:true});}
  function hide(){overlay.hidden=true;clearInput();}
  function button(text,action,primary=false){return `<button type="button" data-action="${action}" class="${primary?'primary':''}">${text}</button>`;}
  function startScreen(){clearTimeout(toastTimer);toast.classList.remove('visible');game.reset();camera=0;updateHUD();show('<p class="kicker">BIENVENIDO AL TALLER</p><div class="hero-icon">✂</div><h2>Las ideas necesitan un primer salto.</h2><p>Ayuda a <strong>Rollo</strong>, el robot de cartón, a superar cinco bloqueos creativos y recoger las ideas que dejan atrás.</p><p class="hint">Písalos desde arriba. Si te tocan de lado, pierdes.<br>Recoge cada estrella para descubrir una reflexión.</p><div class="buttons">'+button('¡Vamos a crear! →','start',true)+'</div>');}
  function announce(message){toast.textContent=message;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),4000);}
  function updateHUD(){document.getElementById('progress').textContent=`BLOQUEOS SUPERADOS · ${game.kills} / 5`;document.getElementById('collected').textContent=`${game.collected.size}/5`;document.getElementById('pause-button').disabled=game.state==='start'||game.state==='lost';}
  function pause(){if(game.state!=='playing')return;game.state='paused';show('<p class="kicker">RESPIRA UN MOMENTO</p><h2>Hasta las ideas necesitan una pausa.</h2><p>La aventura te espera justo donde la dejaste.</p><div class="buttons">'+button('Seguir creando','resume',true)+button('Volver al inicio','home')+'</div>');}
  function victory(){game.state='victory';updateHUD();show('<p class="kicker">5 DE 5 · BLOQUEOS SUPERADOS</p><div class="hero-icon">✦</div><h2>¡Tu creatividad ganó!</h2><p>Rollo llegó lejos con cartón, curiosidad y un salto a la vez. Tú también puedes seguir construyendo ideas.</p><p class="hint">Las cinco reflexiones están disponibles para volver a leerlas.</p><div class="buttons">'+button('Ver las 5 reflexiones','gallery',true)+button('Jugar de nuevo','restart')+'</div>');}
  function lose(){game.state='lost';updateHUD();show('<p class="kicker">UN TROPIEZO NO DEFINE TU CAMINO</p><div class="hero-icon">☁</div><h2>Fuiste victima del bloqueo creativo</h2><p>Vuelve al inicio y prueba otra vez. Recuerda: salta sobre el bloqueo, evita tocarlo de lado.</p><div class="buttons">'+button('Volver al inicio','home',true)+'</div>');}
  function art(id){
    const r=reflections[id];const shapes=[
      '<path d="M110 95 Q140 45 180 92 Q216 45 247 95" fill="none" stroke="#fffdf2" stroke-width="12"/><path d="M180 110v40m-16-15 16 16 16-16" fill="none" stroke="#fffdf2" stroke-width="6"/>',
      '<path d="m180 35 17 33 38 6-27 26 6 38-34-18-34 18 6-38-27-26 38-6z" fill="#fffdf2"/><path d="m164 88 12 12 24-27" fill="none" stroke="#729467" stroke-width="6"/>',
      '<path d="M100 140V88h40v52m35 0V65h40v75m35 0V40h40v100" fill="#fffdf2"/><path d="M90 150h220" stroke="#344536" stroke-width="4"/>',
      '<path d="M155 55a35 35 0 1 1 50 45l-8 20h-29l-8-20a35 35 0 0 1-5-45" fill="#fffdf2"/><path d="M169 132h26m-23 12h20M180 20v-12m-58 48-12-6m126 6 12-6" stroke="#fffdf2" stroke-width="6"/>',
      '<path d="M100 144q10-90 70-65 30-75 78-15 43 25 23 80" fill="#fffdf2"/><path d="m154 113 20 20 40-47" fill="none" stroke="#729467" stroke-width="8"/>'
    ];
    return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 360 175"><rect width="360" height="175" rx="16" fill="${r.color}"/><circle cx="60" cy="42" r="8" fill="#ffffff50"/><circle cx="308" cy="132" r="16" fill="#ffffff40"/>${shapes[id]}</svg>`);
  }
  function reflection(id,back){currentReflection=id;afterReflection=back;game.state='reflection';const r=reflections[id];show(`<p class="kicker">IDEA ${id+1} DE 5 · ${r.name.toUpperCase()}</p><img class="reflection-image" src="${art(id)}" alt="Ilustración sobre ${r.name.toLowerCase()}"><h2>${r.title}</h2><p>${r.text}</p><div class="buttons">${button(back==='gallery'?'Volver a las reflexiones':'Continuar →','close-reflection',true)}</div>`);}
  function gallery(from=game.state){if(from!=='reflection'&&from!=='gallery')returnState=from;game.state='gallery';const unlocked=id=>game.won||game.collected.has(id);show('<p class="kicker">TU CAJA DE IDEAS</p><h2>Pequeñas ideas, grandes pasos.</h2><p>'+(game.won?'Vuelve a cualquiera de las cinco reflexiones.':'Recoge estrellas para guardar las reflexiones aquí.')+'</p><div class="gallery">'+reflections.map((r,i)=>`<button type="button" data-reflection="${i}" ${unlocked(i)?'':'disabled'}><span>${unlocked(i)?r.icon:'◇'}</span>${unlocked(i)?r.name:'Por descubrir'}</button>`).join('')+'</div><div class="buttons">'+button('Volver','close-gallery',true)+'</div>');}
  function closeReflection(){if(afterReflection==='gallery'){gallery('reflection');return;}if(game.won && game.collected.size===5){victory();return;}game.state='playing';hide();}
  panel.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-reflection')){reflection(Number(b.dataset.reflection),'gallery');return;}switch(b.dataset.action){case'start':game.state='playing';hide();break;case'restart':clearTimeout(toastTimer);toast.classList.remove('visible');game.reset();game.state='playing';camera=0;updateHUD();hide();break;case'home':startScreen();break;case'resume':game.state='playing';hide();break;case'gallery':gallery();break;case'close-gallery':if(returnState==='victory')victory();else if(returnState==='start')startScreen();else if(returnState==='lost')lose();else if(returnState==='paused'){game.state='playing';pause();}else{game.state='playing';hide();}break;case'close-reflection':closeReflection();break;}});
  window.addEventListener('keydown',e=>{if(e.key==='Tab'&&!overlay.hidden){const buttons=[...panel.querySelectorAll('button:not(:disabled)')];const i=buttons.indexOf(document.activeElement);e.preventDefault();buttons[(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length]?.focus({preventScroll:true});}});
  document.getElementById('pause-button').addEventListener('click',()=>{if(game.won&&game.state==='playing')victory();else if(game.state==='paused'){game.state='playing';hide();}else pause();});
  document.getElementById('gallery-button').addEventListener('click',()=>{if(game.state==='reflection')return;if(game.state==='gallery')return;gallery();});
  const supported=['ArrowLeft','ArrowRight','ArrowUp','KeyA','KeyD','KeyW','Space'];
  window.addEventListener('keydown',e=>{if(supported.includes(e.code)&&game.state==='playing'){e.preventDefault();keys.add(e.code);if(!e.repeat&&['ArrowUp','KeyW','Space'].includes(e.code))game.jump();}if(e.code==='Escape'){if(game.state==='playing')pause();else if(game.state==='paused'){game.state='playing';hide();}else if(game.state==='reflection')closeReflection();else if(game.state==='gallery')panel.querySelector('[data-action="close-gallery"]').click();}});
  window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{clearInput();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pause();}});
  document.querySelectorAll('[data-control]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(game.state!=='playing')return;b.setPointerCapture(e.pointerId);touch.add(b.dataset.control);b.classList.add('pressed');if(b.dataset.control==='jump')game.jump();});const release=()=>{touch.delete(b.dataset.control);b.classList.remove('pressed');};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);});
  function round(x,y,w,h,r,fill,stroke=colors.outline){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2.5;ctx.stroke();}}
  function ellipse(x,y,rx,ry,fill){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();}
  function text(t,x,y,size=12,color=colors.outline){ctx.fillStyle=color;ctx.font=`700 ${size}px system-ui`;ctx.textAlign='center';ctx.fillText(t,x,y);}
  function cloud(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ellipse(0,0,36,15,'#ffffffde');ellipse(-20,-10,22,20,'#ffffffde');ellipse(12,-16,27,23,'#ffffffde');ellipse(36,-3,22,15,'#ffffffde');ctx.restore();}
  function hill(x,y,w,h,color){ctx.beginPath();ctx.moveTo(x-w,y);ctx.bezierCurveTo(x-w*.45,y-h,x+w*.1,y-h,x+w,y);ctx.lineTo(x+w,500);ctx.lineTo(x-w,500);ctx.closePath();ctx.fillStyle=color;ctx.fill();}
  function star(x,y,r,fill){ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,s=i%2?r*.46:r;const px=x+Math.cos(a)*s,py=y+Math.sin(a)*s;i?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle='#68572e';ctx.lineWidth=2;ctx.stroke();}
  function robot(x,y,scale=1){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);const walking=game.state==='playing'&&game.player.vx?Math.sin(game.time*13)*4:0;
    ellipse(23,77,28,5,'#284d3330');round(7,54+walking,12,20,4,'#c9a274');round(28,54-walking,12,20,4,'#c9a274');round(2,70+walking,20,7,3,'#6a8274');round(25,70-walking,20,7,3,'#6a8274');round(5,27,37,33,8,'#cea46f');ellipse(23,29,17,5,'#e7c899');ctx.strokeStyle='#9c764d';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(9,45);ctx.lineTo(37,51);ctx.stroke();round(-5,32,9,29,3,'#dcc598');round(44,32,9,29,3,'#dcc598');round(0,0,47,29,8,'#d8b17d');ellipse(23,2,21,5,'#e8cfa2');ellipse(13,16,6,6,'#f8f2df');ellipse(34,16,6,6,'#f8f2df');ellipse(14+game.player.facing,16,2.5,3,'#344536');ellipse(34+game.player.facing,16,2.5,3,'#344536');round(18,23,11,3,1,'#85624a',null);ctx.strokeStyle='#344536';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(24,0);ctx.lineTo(24,-12);ctx.stroke();ellipse(24,-14,4,4,'#df7748');round(16,36,14,12,3,'#89a99b');text('✦',23,46,10,'#fffdf2');ctx.restore();}
  function enemy(e){const r=reflections[e.id],x=e.x-camera,y=e.y;ctx.save();ctx.translate(x,y);const wiggle=Math.sin(game.time*5+e.id)*2;ellipse(24,51,30,5,'#284d3330');round(0,wiggle,48,44,12,r.color);round(3,40,13,9,3,'#566450');round(32,40,13,9,3,'#566450');ellipse(14,19+wiggle,7,8,'#fffdf2');ellipse(34,19+wiggle,7,8,'#fffdf2');ellipse(15,20+wiggle,3,4,'#344536');ellipse(33,20+wiggle,3,4,'#344536');ctx.beginPath();ctx.moveTo(8,8+wiggle);ctx.lineTo(20,12+wiggle);ctx.moveTo(28,12+wiggle);ctx.lineTo(40,8+wiggle);ctx.strokeStyle='#344536';ctx.lineWidth=3;ctx.stroke();text(r.icon,24,-12,21);ctx.restore();round(x-46,GROUND+17,140,24,12,'#fffdf2ce',null);text(r.name,x+24,GROUND+33,10);}
  function render(){
    camera=Math.max(0,Math.min(WORLD-960,game.player.x-280));
    const sky=ctx.createLinearGradient(0,0,0,400);sky.addColorStop(0,'#70bcef');sky.addColorStop(1,'#d5edfb');ctx.fillStyle=sky;ctx.fillRect(0,0,960,500);
    ellipse(834-camera*.05,65,34,34,'#fff5bd');for(let i=0;i<7;i++)cloud(i*280-120-camera*.18,70+(i%3)*39,.8+(i%2)*.35);
    for(let i=-1;i<7;i++)hill(i*460-camera*.25,367,410,120+(i%2)*40,'#85bd6c');
    for(let i=-1;i<10;i++)hill(i*400+200-camera*.45,428,390,165,'#63a950');
    ctx.fillStyle='#76b44e';ctx.fillRect(0,GROUND,960,85);ctx.fillStyle='#9cc966';ctx.fillRect(0,GROUND,960,7);
    for(let i=0;i<60;i++){const x=i*80-camera;ctx.strokeStyle='#529842';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,465);ctx.lineTo(x-3,457);ctx.moveTo(x,465);ctx.lineTo(x+5,456);ctx.stroke();if(i%3===0){ellipse(x+25,455,3,3,'#fff0b3');ellipse(x+25,455,1,1,'#dfa044');}}
    for(const s of game.platforms){round(s.x-camera,s.y,s.w,s.h,4,'#c99b66');ctx.strokeStyle='#9f764f';ctx.lineWidth=1;for(let k=0;k<s.w;k+=12){ctx.beginPath();ctx.moveTo(s.x-camera+k,s.y+4);ctx.lineTo(s.x-camera+k+5,s.y+12);ctx.stroke();}}
    for(let i=0;i<5;i++){const x=360+i*580-camera;ctx.strokeStyle='#8a6c48';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x,GROUND);ctx.lineTo(x,GROUND-47);ctx.stroke();round(x-40,GROUND-74,80,30,4,'#f5e7bd');text(`ZONA 0${i+1}`,x,GROUND-54,11);}
    for(const e of game.enemies)if(e.alive)enemy(e);
    for(const d of game.pickups)if(!game.collected.has(d.id)){const y=d.y+16+Math.sin(game.time*4)*4;ellipse(d.x-camera+16,y,25,25,'#fff6b640');star(d.x-camera+16,y,16,'#ffe290');}
    robot(game.player.x-camera,game.player.y);
    if(game.won){round(760,22,180,42,10,'#fffdf2');text('¡5 bloqueos superados!',850,40,11);text('Recoge las ideas o pulsa Ⅱ',850,55,9);}
  }
  function frame(now){const dt=last?(now-last)/1000:0;last=now;game.tick(dt,{left:keys.has('ArrowLeft')||keys.has('KeyA')||touch.has('left'),right:keys.has('ArrowRight')||keys.has('KeyD')||touch.has('right')});for(const event of game.events.splice(0)){updateHUD();if(event.type==='lose')lose();if(event.type==='win')announce('¡Ganaste! Recoge tus estrellas para leer las últimas ideas.');if(event.type==='reflection')reflection(event.id,null);}render();requestAnimationFrame(frame);}
  startScreen();requestAnimationFrame(frame);
})();
