(() => {
  'use strict';
  const {Game,reflections,GROUND,WORLD}=window.CraftGame;
  const game=new Game(), canvas=document.getElementById('game'), ctx=canvas.getContext('2d');
  const overlay=document.getElementById('overlay'),panel=document.getElementById('panel'),toast=document.getElementById('toast');
  const keys=new Set(),touch=new Set();let camera=0,last=0,viewWidth=960,returnState='playing',currentReflection=0,afterReflection=null,toastTimer;
  const colors={outline:'#344536',cardboard:'#cb9e68'};
  function clearInput(){keys.clear();touch.clear();game.jumpBuffer=0;document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));}
  function show(html){clearInput();clearTimeout(toastTimer);toast.classList.remove('visible');panel.innerHTML=html;overlay.hidden=false;panel.scrollTop=0;const first=panel.querySelector('button');if(first)first.focus({preventScroll:true});}
  function hide(){overlay.hidden=true;clearInput();updateHUD();}
  function button(text,action,primary=false){return `<button type="button" data-action="${action}" class="${primary?'primary':''}">${text}</button>`;}
  function startScreen(){clearTimeout(toastTimer);toast.classList.remove('visible');game.reset();camera=0;updateHUD();show('<p class="kicker">DISEÑAR COMIENZA POR ESCUCHAR</p><h2>Escucha. Prueba. Vuelve a intentar.</h2><p>Ayuda a CaseroBot a aprender que significa diseñar, perseverar e iterar sin que sea victima de los bloqueos creativos.</p><p class="intro-summary">Recorre el escenario, supera a los cinco enemigos de colores y recoge sus powerups para descubrir reflexiones sobre el diseño en ingeniería. Los enemigos grises también se eliminan al pisarlos, pero no dan reflexiones. Al vencer a los cinco de colores, podrás volver a consultar las cinco reflexiones.</p><p class="hint">Muévete con las flechas o A/D y salta con Espacio, W o ↑. En móvil, usa los botones inferiores. Los enemigos te perseguirán y atacarán: evítalos y písalos desde arriba para vencerlos. Recoge los powerups para leer las reflexiones; el juego se pausará mientras lees. Si un enemigo te golpea, tocas los pinchos o caes en un pozo, pierdes. Pulsa Escape para pausar.</p><div class="buttons">'+button('¡Vamos a crear! →','start',true)+'</div>');}
  function announce(message){toast.textContent=message;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),4000);}
  function updateHUD(){document.getElementById('progress').textContent=`PRINCIPALES SUPERADOS · ${game.kills} / 5`;document.getElementById('collected').textContent=`${game.collected.size}/5`;document.getElementById('pause-button').disabled=game.state==='start'||game.state==='lost';}
  function pause(){if(game.state!=='playing')return;game.state='paused';show('<p class="kicker">RESPIRA UN MOMENTO</p><h2>Hasta las ideas necesitan una pausa.</h2><p>La aventura te espera justo donde la dejaste.</p><div class="buttons">'+button('Seguir creando','resume',true)+button('Volver al inicio','home')+'</div>');}
  function victory(){game.state='victory';updateHUD();show('<p class="kicker">5 DE 5 · ENEMIGOS SUPERADOS</p><div class="hero-icon">✦</div><h2>¡Aprendiste a iterar!</h2><p>Cada iteración te acerca a una solución que responde al usuario. Escuchar, recibir comentarios y probar tus ideas te ayuda a mejorar el diseño.</p><p class="hint">Las cinco reflexiones están disponibles para volver a leerlas.</p><div class="buttons">'+button('Ver las 5 reflexiones','gallery',true)+button('Jugar de nuevo','restart')+'</div>');}
  function lose(){game.state='lost';updateHUD();show('<p class="kicker">UN TROPIEZO NO DEFINE TU CAMINO</p><div class="hero-icon">☁</div><h2 id="death-title"></h2><p>Vuelve al inicio y prueba otra vez. Observa el entorno y aprende de cada intento.</p><div class="buttons">'+button('Volver al inicio','home',true)+'</div>');document.getElementById('death-title').textContent=game.deathMessage;}
  function art(id){return reflections[id].image;}
  function reflection(id,back){currentReflection=id;afterReflection=back;game.state='reflection';const r=reflections[id];show(`<p class="kicker">REFLEXIÓN ${id+1} DE 5 · DISEÑO EN INGENIERÍA</p><h2 class="reflection-title">${r.title}</h2><p>${r.text}</p><img class="reflection-image" src="${art(id)}" alt="${['Diagrama del doble diamante del diseño','Empatía: conexión entre corazón y cerebro','Prototipo de mesa y sillas','Propuesta de diseño construida con materiales disponibles','Prototipo para realizar pruebas e iterar'][id]}"><div class="buttons">${button(back==='gallery'?'Volver a las reflexiones':'Continuar →','close-reflection',true)}</div>`);}
  function gallery(from=game.state){if(from!=='reflection'&&from!=='gallery')returnState=from;game.state='gallery';const unlocked=id=>game.won||game.collected.has(id);show('<p class="kicker">APRENDIZAJES PARA DISEÑAR</p><h2>Escuchar, experimentar e iterar.</h2><p>'+(game.won?'Vuelve a cualquiera de las cinco reflexiones.':'Recoge estrellas para guardar las reflexiones aquí.')+'</p><div class="gallery">'+reflections.map((r,i)=>`<button type="button" data-reflection="${i}" ${unlocked(i)?'':'disabled'}><span>${unlocked(i)?r.icon:'◇'}</span><strong>${unlocked(i)?r.title:'Por descubrir'}</strong></button>`).join('')+'</div><div class="buttons">'+button('Volver','close-gallery',true)+'</div>');}
  function closeReflection(){if(afterReflection==='gallery'){gallery('reflection');return;}if(game.won && game.collected.size===5){victory();return;}game.state='playing';hide();}
  panel.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-reflection')){reflection(Number(b.dataset.reflection),'gallery');return;}switch(b.dataset.action){case'start':game.state='playing';hide();break;case'restart':clearTimeout(toastTimer);toast.classList.remove('visible');game.reset();game.state='playing';camera=0;updateHUD();hide();break;case'home':startScreen();break;case'resume':game.state='playing';hide();break;case'gallery':gallery();break;case'close-gallery':if(returnState==='victory')victory();else if(returnState==='start')startScreen();else if(returnState==='lost')lose();else if(returnState==='paused'){game.state='playing';pause();}else{game.state='playing';hide();}break;case'close-reflection':closeReflection();break;}});
  window.addEventListener('keydown',e=>{if(e.key==='Tab'&&!overlay.hidden){const buttons=[...panel.querySelectorAll('button:not(:disabled)')];const i=buttons.indexOf(document.activeElement);e.preventDefault();buttons[(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length]?.focus({preventScroll:true});}});
  document.getElementById('pause-button').addEventListener('click',()=>{if(game.won&&game.state==='playing')victory();else if(game.state==='paused'){game.state='playing';hide();}else pause();});
  document.getElementById('gallery-button').addEventListener('click',()=>{if(game.state==='reflection')return;if(game.state==='gallery')return;gallery();});
  const supported=['ArrowLeft','ArrowRight','ArrowUp','KeyA','KeyD','KeyW','Space'];
  window.addEventListener('keydown',e=>{if(supported.includes(e.code)&&game.state==='playing'){e.preventDefault();keys.add(e.code);if(!e.repeat&&['ArrowUp','KeyW','Space'].includes(e.code))game.jump();}if(e.code==='Escape'){if(game.state==='playing')pause();else if(game.state==='paused'){game.state='playing';hide();}else if(game.state==='reflection')closeReflection();else if(game.state==='gallery')panel.querySelector('[data-action="close-gallery"]').click();}});
  window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{clearInput();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pause();}});
  document.querySelectorAll('[data-control]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(game.state!=='playing')return;b.setPointerCapture(e.pointerId);touch.add(b.dataset.control);b.classList.add('pressed');if(b.dataset.control==='jump')game.jump();});const release=()=>{touch.delete(b.dataset.control);b.classList.remove('pressed');};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);});
  function round(x,y,w,h,r,fill,stroke=colors.outline){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2.5;ctx.stroke();}}
  function ellipse(x,y,rx,ry,fill){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();}
  function text(t,x,y,size=12,color=colors.outline){ctx.fillStyle=color;ctx.font=`700 ${size}px system-ui`;ctx.textAlign='center';ctx.fillText(t,x,y);}
  function cloud(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ellipse(0,0,36,15,'#ffffffde');ellipse(-20,-10,22,20,'#ffffffde');ellipse(12,-16,27,23,'#ffffffde');ellipse(36,-3,22,15,'#ffffffde');ctx.restore();}
  function hill(x,y,w,h,color){ctx.beginPath();ctx.moveTo(x-w,y);ctx.bezierCurveTo(x-w*.45,y-h,x+w*.1,y-h,x+w,y);ctx.lineTo(x+w,500);ctx.lineTo(x-w,500);ctx.closePath();ctx.fillStyle=color;ctx.fill();}
  function star(x,y,r,fill){ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,s=i%2?r*.46:r;const px=x+Math.cos(a)*s,py=y+Math.sin(a)*s;i?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle='#68572e';ctx.lineWidth=2;ctx.stroke();}
  function robot(x,y,scale=1){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);const walking=game.state==='playing'&&game.player.vx?Math.sin(game.time*13)*4:0;
    ellipse(23,77,28,5,'#284d3330');round(7,54+walking,12,20,4,'#c9a274');round(28,54-walking,12,20,4,'#c9a274');round(2,70+walking,20,7,3,'#6a8274');round(25,70-walking,20,7,3,'#6a8274');round(5,27,37,33,8,'#cea46f');ellipse(23,29,17,5,'#e7c899');ctx.strokeStyle='#9c764d';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(9,45);ctx.lineTo(37,51);ctx.stroke();round(-5,32,9,29,3,'#dcc598');round(44,32,9,29,3,'#dcc598');round(0,0,47,29,8,'#d8b17d');ellipse(23,2,21,5,'#e8cfa2');ellipse(13,16,6,6,'#f8f2df');ellipse(34,16,6,6,'#f8f2df');ellipse(14+game.player.facing,16,2.5,3,'#344536');ellipse(34+game.player.facing,16,2.5,3,'#344536');round(18,23,11,3,1,'#85624a',null);ctx.strokeStyle='#344536';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(24,0);ctx.lineTo(24,-12);ctx.stroke();ellipse(24,-14,4,4,'#df7748');round(16,36,14,12,3,'#89a99b');text('✦',23,46,10,'#fffdf2');ctx.restore();}
  function redSpark(x,y,r){ctx.beginPath();ctx.moveTo(x,y-r);ctx.quadraticCurveTo(x+2,y-2,x+r,y);ctx.quadraticCurveTo(x+2,y+2,x,y+r);ctx.quadraticCurveTo(x-2,y+2,x-r,y);ctx.quadraticCurveTo(x-2,y-2,x,y-r);ctx.fillStyle='#d92d38';ctx.fill();ctx.strokeStyle='#a9202b';ctx.lineWidth=1;ctx.stroke();}
  function enemy(e){
    const r={color:e.color},x=e.x-camera,y=e.y;
    for(const t of e.trail){ctx.globalAlpha=t.life/.25*.35;round(t.x-camera,t.y+6,48,35,12,'#d93d3d',null);}ctx.globalAlpha=1;
    if(e.mode==='dash'){ctx.strokeStyle='#df4e48';ctx.lineWidth=3;for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(x+24-e.dir*34,y+11+i*11);ctx.lineTo(x+24-e.dir*(75+i*8),y+11+i*11);ctx.stroke();}}
    ctx.save();ctx.translate(x,y);const wiggle=Math.sin(game.time*5+e.id)*2;const lean=e.mode==='windup'?-e.dir*5:e.mode==='attack'?e.dir*5:0;ctx.translate(lean,0);
    ellipse(24,51,30,5,'#284d3330');round(0,wiggle,48,44,12,r.color);round(3,40,13,9,3,'#566450');round(32,40,13,9,3,'#566450');ellipse(14,19+wiggle,7,8,'#fffdf2');ellipse(34,19+wiggle,7,8,'#fffdf2');
    if(['charge','dash'].includes(e.mode)||e.attackFromDash){redSpark(14,19+wiggle,10);redSpark(34,19+wiggle,10);}else{ellipse(15+e.dir,20+wiggle,3,4,'#344536');ellipse(33+e.dir,20+wiggle,3,4,'#344536');}
    ctx.beginPath();ctx.moveTo(8,8+wiggle);ctx.lineTo(20,12+wiggle);ctx.moveTo(28,12+wiggle);ctx.lineTo(40,8+wiggle);ctx.strokeStyle='#344536';ctx.lineWidth=3;ctx.stroke();
    const armX=e.dir>0?43:5;round(armX+(e.mode==='attack'?e.dir*12:0)-5,27,15,12,5,r.color);ctx.restore();
    if(e.mode==='attack'){const box=game.attackBox(e);if(box.x-camera<viewWidth&&box.x+box.w-camera>0&&box.y<500&&box.y+box.h>0)game.markAttackVisible(e);ctx.save();ctx.beginPath();ctx.rect(box.x-camera,box.y,box.w,box.h);ctx.clip();ctx.strokeStyle=e.attackFromDash?'#ed5850':'#fff5be';ctx.lineWidth=9;ctx.beginPath();const front=e.dir>0?e.x+e.w:e.x;ctx.ellipse(front-camera,e.y+28,68,28,0,-Math.PI/2,Math.PI/2,e.dir<0);ctx.stroke();ctx.strokeStyle='#fffdf2';ctx.lineWidth=3;ctx.stroke();ctx.restore();}
  }
  function render(){
    viewWidth=window.innerWidth<=700?600:960;if(canvas.width!==viewWidth)canvas.width=viewWidth;camera=Math.max(0,Math.min(WORLD-viewWidth,game.player.x-viewWidth*.3));
    const sky=ctx.createLinearGradient(0,0,0,400);sky.addColorStop(0,'#70bcef');sky.addColorStop(1,'#d5edfb');ctx.fillStyle=sky;ctx.fillRect(0,0,viewWidth,500);
    ellipse(viewWidth-126-camera*.05,65,34,34,'#fff5bd');for(let i=0;i<7;i++)cloud(i*280-120-camera*.18,70+(i%3)*39,.8+(i%2)*.35);
    for(let i=-1;i<12;i++)hill(i*460-camera*.25,367,410,120+(i%2)*40,'#85bd6c');
    for(let i=-1;i<15;i++)hill(i*400+200-camera*.45,428,390,165,'#63a950');
    for(const land of game.surfaces.filter(s=>s.ground)){ctx.fillStyle='#76b44e';ctx.fillRect(land.x-camera,GROUND,land.w,85);ctx.fillStyle='#9cc966';ctx.fillRect(land.x-camera,GROUND,land.w,7);}
    for(const pit of game.pits){const x=pit.x-camera;ctx.fillStyle='#283b40';ctx.fillRect(x,GROUND,pit.w,85);ctx.fillStyle='#45634d';ctx.fillRect(x,GROUND,5,85);ctx.fillRect(x+pit.w-5,GROUND,5,85);}

    for(let i=0;i<85;i++){const x=i*80-camera;ctx.strokeStyle='#529842';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,465);ctx.lineTo(x-3,457);ctx.moveTo(x,465);ctx.lineTo(x+5,456);ctx.stroke();if(i%3===0){ellipse(x+25,455,3,3,'#fff0b3');ellipse(x+25,455,1,1,'#dfa044');}}
    for(const s of game.platforms){round(s.x-camera,s.y,s.w,s.h,4,'#c99b66');ctx.strokeStyle='#9f764f';ctx.lineWidth=1;for(let k=0;k<s.w;k+=12){ctx.beginPath();ctx.moveTo(s.x-camera+k,s.y+4);ctx.lineTo(s.x-camera+k+5,s.y+12);ctx.stroke();}}

    for(const spike of game.spikes){ctx.fillStyle='#d5dfd8';ctx.strokeStyle='#344536';ctx.lineWidth=2;for(let x=spike.x;x<spike.x+spike.w;x+=13){ctx.beginPath();ctx.moveTo(x-camera,spike.y+spike.h);ctx.lineTo(x+6.5-camera,spike.y);ctx.lineTo(x+13-camera,spike.y+spike.h);ctx.closePath();ctx.fill();ctx.stroke();}}
    for(const sign of game.signs){const x=sign.x-camera;if(x+sign.w<0||x>viewWidth)continue;ctx.strokeStyle='#8a6c48';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x+sign.w/2,GROUND);ctx.lineTo(x+sign.w/2,sign.y+sign.h);ctx.stroke();round(x,sign.y,sign.w,sign.h,5,'#f5e7bd');text('pozo de bloqueos',x+sign.w/2,sign.y+23,13);text(sign.label,x+sign.w/2,sign.y+42,13);}
    for(const e of game.enemies)if(e.alive)enemy(e);
    for(const d of game.pickups)if(!game.collected.has(d.id)){const y=d.y+16+Math.sin(game.time*4)*4;ellipse(d.x-camera+16,y,25,25,'#fff6b640');star(d.x-camera+16,y,16,'#ffe290');}
    robot(game.player.x-camera,game.player.y);
    if(game.won){round(viewWidth-200,22,180,42,10,'#fffdf2');text('¡5 enemigos superados!',viewWidth-110,40,11);text('Recoge las ideas o pulsa Ⅱ',viewWidth-110,55,9);}
  }
  function frame(now){const dt=last?(now-last)/1000:0;last=now;game.tick(dt,{left:keys.has('ArrowLeft')||keys.has('KeyA')||touch.has('left'),right:keys.has('ArrowRight')||keys.has('KeyD')||touch.has('right')});for(const event of game.events.splice(0)){updateHUD();if(event.type==='lose')lose();if(event.type==='win')announce('¡Ganaste! Recoge tus estrellas para leer las últimas ideas.');if(event.type==='reflection')reflection(event.id,null);}render();requestAnimationFrame(frame);}
  startScreen();requestAnimationFrame(frame);
})();
