const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const {Game,reflections,GROUND,WORLD,DASH_COOLDOWN,BLOCKS,LOW_JUMP,HIGH_JUMP,DETECTION_RANGE}=require('../engine.js');
let count=0;function test(name,run){run();count++;console.log('OK '+name);}
function playing(){const g=new Game(()=>.5);g.state='playing';return g;}
function advance(g,t,input={}){for(let i=0;i<Math.ceil(t*120)&&g.state==='playing';i++){g.tick(1/120,input);g.enemies.forEach(e=>g.markAttackVisible(e));}}
function isolate(g,e=g.enemies[0]){g.enemies.forEach(x=>x.alive=x===e);e.x=620;e.y=GROUND-e.h;e.spawn=620;e.support=0;e.cooldown=99;return e;}
test('Cinco reflexiones e imágenes del Word',()=>{assert.equal(reflections.length,5);reflections.forEach(r=>assert(fs.existsSync(path.join(__dirname,'..',r.image))));});
test('Nivel ampliado, tres pozos y carteles independientes',()=>{const g=playing();assert(WORLD>=6000);assert.equal(g.pits.length,3);assert.deepEqual(g.signs.map(s=>s.label),['culturales','emocionales','perceptuales']);const before=JSON.stringify(g.signs);g.player.x=5000;g.enemies.forEach(e=>g.defeat(e));assert.equal(JSON.stringify(g.signs),before);});
test('No hay plataformas sobre pozos ni tapando carteles',()=>{const g=playing();for(const pit of g.pits)for(const s of g.platforms)assert(!(s.x+s.w>pit.x-200&&s.x<pit.x+pit.w+200));for(const sign of g.signs)for(const s of g.platforms)assert(!g.overlap(sign,s));});
test('Todos los pozos se cruzan saltando desde el suelo',()=>{for(const pit of new Game().pits){const g=playing();g.enemies.forEach(e=>e.alive=false);g.player.x=pit.x-55;g.player.support=g.groundAt(g.player.x).id;g.jump();advance(g,.9,{right:true});assert.equal(g.state,'playing');assert(g.player.x>pit.x+pit.w);assert(g.player.grounded);}});
test('Se restan uno o dos grises del suelo por tramo, con generación segura',()=>{for(const r of [.01,.5,.99]){const g=new Game(()=>r);assert(g.greyCounts.every(n=>n>=3&&n<=4));const original=4+Math.min(2,Math.floor(r*3));assert(g.greyCounts.every(n=>original-n>=1&&original-n<=2));assert.equal(g.enemies.filter(e=>e.kind==='main').length,5);g.enemies.forEach(e=>{assert(g.groundAt(e.x+e.w/2));assert(!g.spikes.some(s=>g.overlap(e,s)));});}});
test('Nombres aleatorios de las categorías correctas y estables',()=>{const g=playing();const names=g.enemies.filter(e=>e.kind==='main').map(e=>e.blockName);g.enemies.filter(e=>e.kind==='main').forEach(e=>assert(BLOCKS[e.category].includes(e.blockName)));g.tick(1/60);assert.deepEqual(g.enemies.filter(e=>e.kind==='main').map(e=>e.blockName),names);});
test('Movimiento, salto, plataforma y protección de 0,5 segundos',()=>{const g=playing();g.enemies.forEach(e=>e.alive=false);g.jump();g.tick(1/60);assert(g.player.vy<0);const s=g.platforms[0];g.spikes=g.spikes.filter(sp=>sp.y+sp.h!==s.y);g.player.x=s.x+30;g.player.y=s.y-g.player.h-2;g.player.vy=180;g.player.grounded=false;g.tick(1/120);g.tick(1/120);assert(g.player.grounded);assert(g.player.feetTimer>.48);advance(g,.51);assert.equal(g.player.feetTimer,0);});
test('Protección de pies elimina al enemigo que sube por debajo',()=>{const g=playing(),e=isolate(g),s=g.platforms[0];g.spikes=g.spikes.filter(sp=>sp.y+sp.h!==s.y);g.player.x=s.x+50;g.player.y=s.y-g.player.h;g.player.support=s.id;g.player.feetTimer=.5;e.x=g.player.x;e.y=s.y-4;e.vy=-180;e.grounded=false;e.jumpVx=0;e.mode='recover';e.timer=1;g.tick(1/120);assert(!e.alive);assert.equal(g.state,'playing');assert.equal(g.kills,1);});
test('La protección no cubre torso ni se renueva estando quieto',()=>{const g=playing(),e=isolate(g);g.player.x=620;g.player.feetTimer=.5;g.tick(1/120);assert.equal(g.state,'lost');const h=playing();h.enemies.forEach(e=>e.alive=false);const s=h.platforms[0];h.spikes=h.spikes.filter(sp=>sp.y+sp.h!==s.y);h.player.x=s.x+30;h.player.y=s.y-h.player.h;h.player.support=s.id;h.player.feetTimer=.1;advance(h,.3);assert.equal(h.player.feetTimer,0);});
test('Fuera de los 0,5 segundos un golpe en pies vuelve a causar daño',()=>{const g=playing(),e=isolate(g),s=g.platforms[0];g.spikes=g.spikes.filter(sp=>sp.y+sp.h!==s.y);g.player.x=s.x+50;g.player.y=s.y-g.player.h;g.player.support=s.id;g.player.feetTimer=0;e.x=g.player.x;e.y=s.y-4;e.vy=-100;e.grounded=false;e.jumpVx=0;e.mode='recover';e.timer=1;g.tick(1/120);assert.equal(g.state,'lost');assert(e.alive);});
test('Pisotones en grises no generan reflexiones ni victoria',()=>{const g=playing();g.enemies.filter(e=>e.kind==='grey').forEach(e=>g.defeat(e));assert.equal(g.kills,0);assert.equal(g.pickups.length,0);assert(!g.won);assert(g.greyKills>=12);});
test('Grises patrullan sin ataque y saltan menos',()=>{const g=playing(),e=isolate(g,g.enemies.find(e=>e.kind==='grey'));g.player.x=e.x+100;let maxHeight=0;for(let i=0;i<1000;i++){g.enemyStep(e,1/120);maxHeight=Math.max(maxHeight,GROUND-e.y-e.h);assert.equal(e.mode,'idle');assert(!e.active);assert.equal(e.trail.length,0);assert(!g.spikes.some(s=>g.overlap(e,s)));}assert(maxHeight<300);assert(e.vy>=LOW_JUMP);});
test('Derrota por principal muestra su nombre',()=>{const g=playing(),e=isolate(g);g.player.x=e.x;g.tick(1/120);assert.equal(g.deathMessage,`Has sido victima de ${e.blockName}`);});
test('Grises y pinchos comparten el mensaje solicitado',()=>{const expected='Has sido victima de las malas decisiones de diseño';const g=playing(),e=isolate(g,g.enemies.find(e=>e.kind==='grey'));g.player.x=e.x;g.tick(1/120);assert.equal(g.deathMessage,expected);for(const spike of new Game(()=>.5).spikes){const h=playing();h.enemies.forEach(e=>e.alive=false);h.player.x=spike.x;h.player.y=spike.y-h.player.h+2;h.tick(1/120);assert.equal(h.deathMessage,expected);}});
test('Cada pozo identifica su categoría al perder',()=>{for(const pit of new Game().pits){const g=playing();g.enemies.forEach(e=>e.alive=false);g.player.x=pit.x+45;advance(g,1);assert.equal(g.deathMessage,`Has sido victima de un bloqueo ${pit.type}.`);}});
test('Dash con estela y seis segundos de recarga',()=>{const g=playing(),e=isolate(g);g.player.x=320;e.cooldown=0;g.enemyStep(e,1/120);assert.equal(e.mode,'charge');for(let i=0;i<56;i++)g.enemyStep(e,1/120);assert.equal(e.mode,'dash');assert(e.trail.length>0);assert(e.cooldown>5.9&&e.cooldown<=DASH_COOLDOWN);e.mode='idle';e.x=620;g.enemyStep(e,1/120);assert.notEqual(e.mode,'charge');});
test('Dash prepara barrido antes de impactar y el barrido hace daño',()=>{const g=playing(),e=isolate(g);e.x=600;e.mode='dash';e.timer=.4;e.dashDir=-1;g.player.x=510;g.enemyStep(e,1/120);assert.equal(e.mode,'windup');assert(e.attackFromDash);advance(g,.3);assert.equal(g.state,'lost');});
test('Principales guardan distancia y no saltan directamente a los pies',()=>{const g=playing(),e=isolate(g);g.player.x=536.5;g.pursue(e);assert(e.vx===0);const s=g.platforms[0];g.spikes=g.spikes.filter(sp=>sp.y+sp.h!==s.y);g.player.x=s.x+50;g.player.y=s.y-g.player.h;g.player.support=s.id;assert(!g.startJump(e,s,g.player.x+g.player.w/2));});
test('Pueden subir plataformas por un costado seguro',()=>{const g=playing(),e=isolate(g),s=g.platforms[0];g.spikes=g.spikes.filter(sp=>sp.y+sp.h!==s.y);e.x=440;g.player.x=s.x+35;g.player.y=s.y-g.player.h;g.player.support=s.id;let climbed=false;for(let i=0;i<800;i++){g.enemyStep(e,1/120);assert(!g.spikes.some(sp=>g.overlap(e,sp)));if(e.grounded&&e.support===s.id){climbed=true;break;}}assert(climbed);});
test('Los enemigos evitan pinchos incluso al hacer dash',()=>{for(const kind of ['main','grey']){const g=playing(),e=isolate(g,kind==='main'?g.enemies[0]:g.enemies.find(e=>e.kind==='grey'));const spike=g.spikes[0];e.x=spike.x-e.w-20;e.min=e.x-100;e.max=e.x+200;g.player.x=spike.x+200;e.cooldown=0;if(kind==='main'){e.mode='dash';e.timer=.5;e.dashDir=1;}for(let i=0;i<600;i++){g.enemyStep(e,1/120);assert(!g.spikes.some(s=>g.overlap(e,s)));}}});
test('Powerups en puntos seguros y pausa de todos los tiempos',()=>{const g=playing(),e=isolate(g);e.x=g.spikes[0].x;g.defeat(e);const d=g.pickups[0];assert(!g.spikes.some(s=>g.overlap(d,s)));g.player.x=d.x;g.tick(1/60);assert.equal(g.state,'reflection');const time=g.time;g.tick(1);assert.equal(g.time,time);});
test('Victoria por cinco principales y reinicio completo',()=>{const g=playing();g.enemies.filter(e=>e.kind==='main').forEach(e=>g.defeat(e));assert(g.won);assert.equal(g.kills,5);assert.equal(g.pickups.length,5);assert(g.enemies.some(e=>e.kind==='grey'&&e.alive));g.reset();assert.equal(g.state,'start');assert.equal(g.kills,0);assert.equal(g.greyKills,0);assert.equal(g.player.feetTimer,0);assert.equal(g.deathMessage,'');assert.equal(g.pickups.length,0);assert(g.enemies.every(e=>e.alive));});
test('La protección no alcanza grises que caminan bajo la plataforma',()=>{const g=playing(),e=isolate(g,g.enemies.find(e=>e.kind==='grey')),platform=g.platforms[0];g.spikes=g.spikes.filter(sp=>sp.y+sp.h!==platform.y);g.player.x=platform.x+60;g.player.y=platform.y-g.player.h;g.player.support=platform.id;g.player.feetTimer=.5;e.x=g.player.x;e.y=GROUND-e.h;e.min=e.x-20;e.max=e.x+20;e.hopTimer=99;advance(g,.49);assert(e.alive);assert.equal(g.greyKills,0);assert.equal(g.state,'playing');});
test('Pisotón directo sobre gris y principal sigue eliminando correctamente',()=>{for(const kind of ['grey','main']){const g=playing(),e=isolate(g,kind==='main'?g.enemies[0]:g.enemies.find(e=>e.kind==='grey'));g.player.x=e.x;g.player.y=e.y-g.player.h-1;g.player.vy=200;g.player.grounded=false;g.tick(1/60);assert(!e.alive);assert(g.player.vy<0);assert.equal(g.state,'playing');}});
test('Los ataques de pies no alcanzan enemigos separados verticalmente',()=>{const g=playing(),e=isolate(g);g.player.feetTimer=.5;e.x=g.player.x;e.y=g.player.y+g.player.h+3;assert(!g.feetHit(e));e.y=g.player.y+g.player.h-7;assert(!g.feetHit(e));e.y=g.player.y+g.player.h-2;assert(g.feetHit(e));});
test('Nombres de todas las categorías explican el bloqueo creativo',()=>{for(const [category,names] of Object.entries(BLOCKS)){const label={culturales:'cultural',emocionales:'emocional',perceptuales:'perceptual'}[category];names.forEach(name=>assert(name.startsWith(`un bloqueo creativo ${label} por `)));}});
test('Los principales tienen cinco colores saturados distintos de los grises',()=>{const g=playing(),colors=g.enemies.filter(e=>e.kind==='main').map(e=>e.color);assert.equal(new Set(colors).size,5);for(const color of colors){const rgb=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16));assert((Math.max(...rgb)-Math.min(...rgb))/Math.max(...rgb)>.55);assert.notEqual(color,g.enemies.find(e=>e.kind==='grey').color);}});
test('Los grises suben una plataforma baja sin perseguir ni atacar',()=>{const g=playing(),e=isolate(g,g.enemies.find(e=>e.kind==='grey')),platform=g.platforms[0];g.spikes=g.spikes.filter(sp=>sp.y+sp.h!==platform.y);e.x=platform.x+50;e.min=platform.x;e.max=platform.x+100;e.hopTimer=0;let landed=false;for(let i=0;i<150;i++){g.enemyStep(e,1/120);if(e.grounded&&e.support===platform.id){landed=true;break;}}assert(landed);assert(!e.active);assert.equal(e.mode,'idle');});
test('Los principales eligen salto bajo o alto según la altura',()=>{const g=playing(),e=isolate(g);assert.equal(g.jumpVelocity(e,g.platforms[0]),LOW_JUMP);assert.equal(g.jumpVelocity(e,g.platforms[1]),HIGH_JUMP);assert.equal(g.jumpVelocity({...e,kind:'grey'},g.platforms[1]),LOW_JUMP);});
test('Un principal llega a la plataforma alta directamente desde el suelo',()=>{const g=playing(),e=isolate(g),platform=g.platforms[1];g.spikes=[];e.x=380;g.player.x=platform.x+110;g.player.y=platform.y-g.player.h;g.player.support=platform.id;g.pursue(e);assert.equal(e.vy,HIGH_JUMP);let landed=false;for(let i=0;i<200;i++){g.enemyStep(e,1/120);if(e.grounded){assert.equal(e.support,platform.id);landed=true;break;}}assert(landed);});
test('La detección se amplía a 1200 píxeles y no afecta a los grises',()=>{assert.equal(DETECTION_RANGE,1200);const g=playing(),e=isolate(g);e.x=1000;g.player.x=65;g.enemyStep(e,1/120);assert(e.active);const grey=g.enemies.find(e=>e.kind==='grey');grey.x=1000;g.enemyStep(grey,1/120);assert(!grey.active);});
test('Aparición en plataformas: umbral del 60 % y máximo un gris',()=>{for(const rng of [.01,.59,.6,.99]){const g=new Game(()=>rng);for(const platform of g.platforms){const on=g.enemies.filter(e=>e.kind==='grey'&&e.spawnSupport===platform.id);assert.equal(on.length,rng<.6?1:0);on.forEach(e=>assert(!g.spikes.some(sp=>g.overlap(e,sp))));}}});
test('Pinchos agrupados de dos a cuatro dentro de cada plataforma, sin suelo',()=>{for(const rng of [.01,.5,.99]){const g=new Game(()=>rng);assert.equal(g.spikes.length,g.platforms.length);for(const platform of g.platforms){const cluster=g.spikes.filter(sp=>sp.y+sp.h===platform.y&&sp.x>=platform.x&&sp.x+sp.w<=platform.x+platform.w);assert.equal(cluster.length,1);assert(cluster[0].count>=2&&cluster[0].count<=4);assert.equal(cluster[0].w,cluster[0].count*13);}assert(!g.spikes.some(sp=>sp.y+sp.h===GROUND));}});
test('Grises y principales saltan un grupo de pinchos en su dirección',()=>{for(const kind of ['grey','main'])for(const dir of [-1,1]){const g=playing(),e=isolate(g,kind==='main'?g.enemies[0]:g.enemies.find(e=>e.kind==='grey')),platform=g.platforms[0];g.spikes=[{x:platform.x+70,y:platform.y-18,w:26,h:18}];e.x=dir>0?platform.x+14:platform.x+105;e.y=platform.y-e.h;e.support=platform.id;e.dir=dir;e.min=platform.x;e.max=platform.x+platform.w-e.w;g.player.x=dir>0?platform.x+350:platform.x-300;g.player.y=e.y;assert(g.jumpObstacle(e,dir));assert(e.vy<0);let landed=false;for(let i=0;i<170;i++){g.enemyStep(e,1/120);assert(!g.spikes.some(sp=>g.overlap(e,sp)));if(e.grounded){landed=true;break;}}assert(landed);}});
test('Dash prioritario sobre plataforma y detenido antes del borde',()=>{const g=playing(),e=isolate(g),platform=g.platforms[0];g.spikes=[];e.x=platform.x+20;e.y=platform.y-e.h;e.support=platform.id;e.cooldown=0;g.player.x=e.x+250;g.player.y=platform.y-g.player.h;g.enemyStep(e,1/120);assert.equal(e.mode,'charge');for(let i=0;i<110;i++){g.enemyStep(e,1/120);assert(e.x>=platform.x);assert(e.x+e.w<=platform.x+platform.w);assert(e.grounded);}assert.notEqual(e.mode,'dash');});
test('Dash detenido ante el pozo y prohibido en el aire',()=>{const g=playing(),e=isolate(g),pit=g.pits[0];e.x=pit.x-e.w-20;e.mode='dash';e.timer=.5;e.dashDir=1;g.player.x=pit.x+300;g.enemyStep(e,1/120);assert.equal(e.mode,'recover');assert(e.x+e.w<pit.x);e.mode='idle';e.cooldown=0;e.x=600;e.y=100;e.grounded=false;e.support=null;g.player.x=900;g.player.y=100;g.enemyStep(e,1/120);assert.notEqual(e.mode,'charge');assert.notEqual(e.mode,'dash');});
test('Un segundo gris no puede reservar ni aterrizar en una plataforma ocupada',()=>{const g=playing(),platform=g.platforms[0],resident=g.enemies.find(e=>e.spawnSupport===platform.id),other=g.enemies.find(e=>e.kind==='grey'&&e!==resident);assert(resident);other.x=platform.x+50;other.y=GROUND-other.h;other.support=0;assert(!g.startJump(other,platform,platform.x+40));other.y=platform.y-other.h-2;other.vy=200;g.move(other,1/60);assert.notEqual(other.support,platform.id);});
test('Recarga de salto gris de 1,5 segundos aplica a todos los saltos',()=>{const g=playing(),e=isolate(g,g.enemies.find(e=>e.kind==='grey')),surface=g.surfaces[0];g.spikes=[];assert(g.startJump(e,surface,e.x+24));assert.equal(e.jumpCooldown,1.5);e.hopTimer=99;e.y=GROUND-e.h;e.vy=0;e.grounded=true;e.support=0;assert(!g.startJump(e,surface,e.x+24));for(let i=0;i<120;i++)g.enemyStep(e,1/120);assert(e.jumpCooldown>0);e.y=GROUND-e.h;e.grounded=true;e.support=0;assert(!g.startJump(e,surface,e.x+24));for(let i=0;i<62;i++)g.enemyStep(e,1/120);e.y=GROUND-e.h;e.grounded=true;e.support=0;assert(g.startJump(e,surface,e.x+24));});
test('Las plataformas ganan 30 píxeles de espacio sin invadir pozos',()=>{const g=playing();assert.deepEqual(g.platforms.slice(0,4).map(p=>p.w),[200,220,210,230]);assert.equal(g.platforms.length,16);});
test('Gris y principal pueden saltar entre plataformas y bajar',()=>{for(const kind of ['grey','main']){const g=playing(),e=isolate(g,kind==='main'?g.enemies[0]:g.enemies.find(e=>e.kind==='grey')),a=g.platforms[0],b=g.platforms[1];g.spikes=[];e.x=a.x+a.w-55;e.y=a.y-e.h;e.support=a.id;e.grounded=true;e.hopTimer=0;g.player.x=b.x+b.w-50;g.player.y=b.y-g.player.h;g.player.support=b.id;for(let i=0;i<120&&e.grounded;i++)g.enemyStep(e,1/120);assert(!e.grounded);assert.equal(e.routeTarget.id,b.id);let landed=false;for(let i=0;i<200;i++){g.enemyStep(e,1/120);if(e.grounded){assert.equal(e.support,b.id);landed=true;break;}}assert(landed);assert(g.startDrop(e));for(let i=0;i<200&&!e.grounded;i++)g.enemyStep(e,1/120);assert(e.grounded);assert(g.surfaces[e.support].ground);}});
test('Si dos grises coinciden, uno abandona la plataforma enseguida',()=>{const g=playing(),platform=g.platforms[0];g.spikes=[];const pair=g.enemies.filter(e=>e.kind==='grey').slice(0,2);g.enemies.forEach(e=>e.alive=pair.includes(e));pair.forEach((e,i)=>{e.x=platform.x+35+i*65;e.y=platform.y-e.h;e.support=platform.id;e.grounded=true;e.hopTimer=99;e.jumpCooldown=1;});pair.forEach(e=>g.enemyStep(e,1/120));assert(pair[0].grounded);assert(!pair[1].grounded);assert.equal(pair[1].dropSurface,platform.id);});
test('Enemigo que sube a los pies en el aire muere incluso si el jugador asciende',()=>{for(const kind of ['grey','main']){const g=playing(),e=isolate(g,kind==='main'?g.enemies[0]:g.enemies.find(e=>e.kind==='grey'));g.spikes=[];g.player.x=600;g.player.y=140;g.player.vy=-200;g.player.grounded=false;g.player.feetTimer=0;e.x=600;e.y=g.player.y+g.player.h+1;e.vy=-600;e.grounded=false;e.support=null;e.jumpVx=0;e.mode='recover';e.timer=1;g.tick(1/120);assert(!e.alive);assert.equal(g.state,'playing');assert(g.player.vy<0);}});
test('Colisión lateral en el aire sigue causando derrota',()=>{const g=playing(),e=isolate(g);g.spikes=[];g.player.x=600;g.player.y=140;g.player.vy=-200;g.player.grounded=false;e.x=600;e.y=160;e.vy=-200;e.grounded=false;e.support=null;e.jumpVx=0;e.mode='recover';e.timer=1;g.tick(1/120);assert(e.alive);assert.equal(g.state,'lost');});
test('La espada espera 0,05 segundos desde su primera imagen visible',()=>{const g=playing(),e=isolate(g);g.spikes=[];e.mode='attack';e.timer=.33;e.dir=-1;e.attackShownAt=null;g.player.x=e.x-60;g.tick(1/120);assert.equal(g.state,'playing');assert(!g.attackCanDamage(e));g.markAttackVisible(e);const shown=g.time;for(let i=0;i<5;i++)g.tick(1/120);assert.equal(g.state,'playing');assert(g.time-shown<.05);g.tick(1/120);assert.equal(g.state,'lost');assert(g.time-shown>=.05-1e-9);});
test('Una espada que no se ha dibujado no puede hacer daño',()=>{const g=playing(),e=isolate(g);g.spikes=[];e.mode='attack';e.timer=.33;e.dir=-1;e.attackShownAt=null;g.player.x=e.x-60;for(let i=0;i<25;i++)g.tick(1/120);assert.equal(g.state,'playing');assert(!g.attackCanDamage(e));});
test('Saltar desde el suelo bajo pinchos detiene la cabeza sin matar',()=>{for(const platform of new Game(()=>.5).platforms){const g=playing();g.enemies.forEach(e=>e.alive=false);const spike=g.spikes.find(sp=>sp.y+sp.h===platform.y&&sp.x>=platform.x&&sp.x<platform.x+platform.w);g.player.x=spike.x;g.jump();advance(g,.8);assert.equal(g.state,'playing');assert(g.player.grounded);assert.equal(g.player.y,GROUND-g.player.h);}});
test('Jugador y enemigos chocan con el techo bajo el grupo de pinchos',()=>{for(const kind of ['player','grey','main']){const g=playing(),platform=g.platforms[1],spike=g.spikes[1];const body=kind==='player'?g.player:g.enemies.find(e=>e.kind===kind);body.x=spike.x;body.y=platform.y+platform.h+1;body.vx=0;body.vy=-300;body.grounded=false;body.support=null;g.move(body,1/120);assert.equal(body.y,platform.y+platform.h);assert.equal(body.vy,0);assert(!g.overlap(body,spike));assert(!body.grounded);}});
test('El tramo sin pinchos permite atravesar la plataforma hacia arriba',()=>{const g=playing(),platform=g.platforms[1],body=g.player;body.x=platform.x+5;body.y=platform.y+platform.h+1;body.vx=0;body.vy=-300;body.grounded=false;g.move(body,1/120);assert(body.y<platform.y+platform.h);assert(body.vy<0);});
test('El dash comienza dentro de su alcance y antes se acerca sin gastar recarga',()=>{const g=playing(),e=isolate(g);g.spikes=[];e.x=900;e.cooldown=0;g.player.x=500;g.enemyStep(e,1/120);assert.equal(e.mode,'idle');assert(e.vx<0);assert.equal(e.cooldown,0);let charged=false;for(let i=0;i<200;i++){const distance=Math.abs(g.player.x+g.player.w/2-e.x-e.w/2);g.enemyStep(e,1/120);if(e.mode==='charge'){assert(distance<=320);charged=true;break;}}assert(charged);let attacked=false;for(let i=0;i<130;i++){g.enemyStep(e,1/120);if(e.mode==='windup'&&e.attackFromDash){attacked=true;break;}}assert(attacked);});
console.log(`${count} comprobaciones correctas.`);


